const data = [
  {
    key: 1,
    name: 'Name 1',
    field1: 'value1',
    field2: 'value2',
    field3: 'value3',
    field4: 'value4',
    field5: 'value5',
    field6: 'value6',
    field7: 'value7',
  },
  {
    key: 2,
    name: 'Name 2',
    field1: 'value1',
    field2: 'value2',
    field3: 'value3',
    field4: 'value4',
    field5: 'value5',
    field6: 'value6',
    field7: 'value7',
  },
  {
    key: 3,
    name: 'Name 3',
    field1: 'value1',
    field2: 'value2',
    field3: 'value3',
    field4: 'value4',
    field5: 'value5',
    field6: 'value6',
    field7: 'value7',
  },
  {
    key: 4,
    name: 'Name 4',
    field1: 'value1',
    field2: 'value2',
    field3: 'value3',
    field4: 'value4',
    field5: 'value5',
    field6: 'value6',
    field7: 'value7',
  },
  {
    key: 5,
    name: 'Name 5',
    field1: 'value1',
    field2: 'value2',
    field3: 'value3',
    field4: 'value4',
    field5: 'value5',
    field6: 'value6',
    field7: 'value7',
  },
  {
    key: 6,
    name: 'Name 6',
    field1: 'value1',
    field2: 'value2',
    field3: 'value3',
    field4: 'value4',
    field5: 'value5',
    field6: 'value6',
    field7: 'value7',
  },
  {
    key: 7,
    name: 'Name 7',
    field1: 'value1',
    field2: 'value2',
    field3: 'value3',
    field4: 'value4',
    field5: 'value5',
    field6: 'value6',
    field7: 'value7',
  },
];

export default data;
